### ISSUE TITLE
Any way to access the knowledge base id?

### ISSUE THREAD

**Issue by merojosa** [maxtybar/bedrock-agents-cdk#4]
Hello, congrats for this construct. I've been using it for a couple days and it's amazing.

I'm wondering if you have any idea how can I access a knowledge base id? I'm aware that I can get the knowlege base name and then use list_knowledge_bases function to filter by the given name. However, it's kinda cumbersome this flow.

Do you have any ideas? I'm willing to do some research and open a PR if possible.

**Comment by maxtybar** [comment]
@merojosa Hey! Glad you found it useful! Are you talking about getting id from the construct? I.e. `const kb = BedrockKnowledgeBase( ...` and `kb.attrId = ...` ? I am going to add that soon, just a little bit strapped with time at the moment but this is a next thing I wanted to update - be able to retrieve agent's and knowledge base's id (and other parameters) from construct definition. If you are talking about a general `boto3` api call to get knowledge base id from knowledge base name then I am afraid this functionality doesn't exist (at least as I write this comment). I am not sure if Amazon Bedrock Agents/KB team supports PR requests to be honest. Hope this helps!

**Comment by merojosa** [comment]
Jmmm, not sure if I get it. What I mean is that I need something like:

```
  const bedrockKb = new BedrockKnowledgeBase(
    stack,
    "BedrockOpenSearchKnowledgeBase",
    {
      ...
    }
  );

  console.log(bedrockKb.knowledgeBaseId, bedrockKb.dataSourceId)
```

Of course, instead of the console.log, I'd pass those ids as environment variables in my Python Lambda (in my case, I'm using sst). Then, in my Lambda I'll use them like:

```
    response = bedrock_client.start_ingestion_job(
        knowledgeBaseId=os.environ['KB_ID'],
        dataSourceId=os.environ['DS_ID'],
    )
```

Does that make sense?

**Comment by maxtybar** [comment]
Yes, it does. That's what I meant in the first part of my answer, apologize if I wasn't clear. I am working on adding this functionality, should update this soon. Stay tuned!

**Comment by merojosa** [comment]
No worries, my bad. Thanks a lot, looking forward to it!

**Comment by maxtybar** [comment]
This is now added in v0.0.7. You can retrieve `knowledgeBaseId`, `dataSourceId` and `knowledgeBaseArn` from `BedrockKnowledgeBase` constructs as well as `agentId` and `agentArn` from `BedrockAgent` construct. Closing this issue.

**Comment by merojosa** [comment]
Awesome work @maxtybar, thanks a lot!
