### ISSUE TITLE
UserInput setting is missing

### ISSUE THREAD

**Issue by mirodrr** [maxtybar/bedrock-agents-cdk#7]
There is no option to configure the "User Input" setting for an Agent as shown here in the console UI
![image](https://github.com/maxtybar/bedrock-agents-cdk/assets/113373534/3d00455a-3075-430c-8906-bd3f805bc116)

**Comment by maxtybar** [comment]
@mirodrr It is not configurable at the moment as it can't be triggered with the API call and only works through the console. Just wanted to make sure we are on the same page - I do work for AWS but this a personal project and not affiliated with the Bedrock service team. I try to make changes and look for updates in my free time but if you see there are updates being made that you would like to incorporate you are free to make the updates and submit a PR so I can merge it. Thank you!

**Comment by mirodrr** [comment]
Ah okay, then there's nothing you can do about it. Thanks for the info, you can close this ticket.

**Comment by mirodrr** [comment]
Nothing can be done about this currently. Bedrock team needs to update their API. Closing
